version: '3.1'

services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: sssyayayiooo/kafkadocker_kafka:latest
    container_name: kafka
    restart: always
    ports:
      - 9092:9092
    environment:
#   if you want to be able to connect from external components and run docker natively, you can set KAFKA_ADVERTISED_HOST_NAME to the IP of your host (e.g. the output of ifconfig en0) if en0 is your main interface.
#   if you want to be able to connect from external components and run docker in docker-machine, you can set KAFKA_ADVERTISED_HOST_NAME to the IP of your docker-machine (e.g. the output of docker-machine ip local) if local is your docker-machine name. i.e. if your docker-machine IP address is 192.168.99.100
      KAFKA_ADVERTISED_HOST_NAME: "192.168.1.4"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "api-log:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  nimbus:
    image: storm:latest
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - 6627:6627

  supervisor:
    image: storm:latest
    container_name: supervisor
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
      - zookeeper
    restart: always

  ui:
    image: storm:latest
    container_name: storm-ui
    command: storm ui
    depends_on:
      - nimbus
      - zookeeper
    links:
      - nimbus
    restart: always
    ports:
      - 8080:8080

